name: CI

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22.3.0'

    - name: Install dependencies
      run: yarn install

    - name: Build expo application
      run: npx expo export --platform web

    - name: Copy files to VPS
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: 22
        source: ./dist,./Dockerfile
        target: ${{ secrets.PROJECT_PATH }}

  deploy:
    name: Deploy to VPS
    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: 22
        script: |
          cd ${{ secrets.PROJECT_PATH }}
          docker stop editor || true
          docker rm editor || true
          docker image rm image-editor:latest || true
          docker build -f ${{ secrets.PROJECT_PATH }}/DockerFile -t image-editor:latest .
          docker run -d --name editor -p 3000:3000 --restart always image-editor:latest
          rm DockerFile
          rm -rf dist